package com.tzutalin.dlibtest;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.graphics.ImageFormat;
import android.graphics.Matrix;
import android.graphics.RectF;
import android.graphics.SurfaceTexture;
import android.hardware.camera2.CameraAccessException;
import android.hardware.camera2.CameraCaptureSession;
import android.hardware.camera2.CameraCharacteristics;
import android.hardware.camera2.CameraDevice;
import android.hardware.camera2.CameraManager;
import android.hardware.camera2.CaptureRequest;
import android.hardware.camera2.CaptureResult;
import android.hardware.camera2.TotalCaptureResult;
import android.hardware.camera2.params.StreamConfigurationMap;
import android.media.ImageReader;
import android.os.Handler;
import android.os.HandlerThread;
import android.support.annotation.NonNull;
import android.support.v4.app.ActivityCompat;
import android.util.Log;
import android.util.Size;
import android.util.SparseArray;
import android.view.Surface;
import android.view.TextureView;

import com.tzutalin.dlib.AutoFitTextureView;
import com.tzutalin.dlib.Constants;
import com.tzutalin.dlib.FaceDetectListener;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Random;
import java.util.concurrent.Semaphore;
import java.util.concurrent.TimeUnit;

import hugo.weaving.DebugLog;

/**
 * Function: Face Out SDK Class
 * Created on 2020/3/27.
 *
 * @author Wangpei
 * Email: wangpei@bamboocloud.cn
 */
public class FaceDetectSDK {

    private volatile static FaceDetectSDK faceSDK;

    /**
     * The camera preview size will be chosen to be the smallest frame by pixel size capable of
     * containing a DESIRED_SIZE x DESIRED_SIZE square.
     */
    private int mMinPreSize = 320;


    private Size mPreviewSize;

    /**
     * A {@link Semaphore} to prevent the app from exiting before closing the camera.
     */
    private final Semaphore cameraOpenCloseLock = new Semaphore(1);

    /**
     * A reference to the opened {@link CameraDevice}.
     */
    private CameraDevice cameraDevice;

    /**
     * {@link CaptureRequest.Builder} for the camera preview
     */
    private CaptureRequest.Builder previewRequestBuilder;

    /**
     * {@link CaptureRequest} generated by {@link #previewRequestBuilder}
     */
    private CaptureRequest previewRequest;

    /**
     * An {@link ImageReader} that handles preview frame capture.
     */
    private ImageReader previewReader;

    /**
     * A {@link CameraCaptureSession } for camera preview.
     */
    private CameraCaptureSession captureSession;

    /**
     * 用于在后台运行任务。
     */
    private Handler backgroundHandler;

    /**
     * 视频每一帧的监听
     */
    private OnGetImageListener mOnGetPreviewListener = new OnGetImageListener();

    /**
     * Context
     */
    private Activity mContext;

    /**
     * 检测回调
     */
    private FaceDetectListener mListener;

    /**
     * 存储的全部检测类型
     */
    private ArrayList<Integer> mMotions = new ArrayList<>(3);

    /**
     * 正在检测的序号
     */
    private int detectingIndex = 0;

    /**
     * 是否直接设置检测类型
     */
    private boolean isSetMotions = false;

    /**
     * 随机的校验次数
     */
    private int mMotionSum;

    /**
     * 最后的检测顺序
     */
    private ArrayList<Integer> mLastMotions;

    /**
     * 是否只支持张嘴检测
     */
    private boolean isOnlyMouth = false;

    /**
     * 是否只支持摇头检测
     */
    private boolean isOnlyHead = false;

    /**
     * 是否只支持眨眼检测
     */
    private boolean isOnlyEye = false;

    private AutoFitTextureView mTextTrueView;


    /**
     * 用于运行不应阻塞UI的任务的附加线程。
     */
    private HandlerThread backgroundThread;

    /**
     * 用于运行推理的附加线程，以免阻塞相机。
     */
    private HandlerThread inferenceThread;

    /**
     * A {@link Handler} for running tasks in the background.
     */
    private Handler inferenceHandler;

    private FaceDetectSDK() {
    }

    public static FaceDetectSDK with() {
        if (faceSDK == null) {
            synchronized (FaceDetectSDK.class) {
                if (faceSDK == null) {
                    faceSDK = new FaceDetectSDK();
                }
            }
        }
        return faceSDK;
    }

    public void destroy() {
        mContext = null;
    }

    public void onStart() {
        startBackgroundThread();
    }

    /**
     * 重置数据
     */
    private void resetMotionsList() {
        mMotions.clear();
        mMotions.add(Constants.MOTION_MOUTH);
        mMotions.add(Constants.MOTION_EYE);
        mMotions.add(Constants.MOTION_HEAD);
    }

    /**
     * 初始化
     *
     * @param context Context
     */
    public FaceDetectSDK init(Activity context
            , AutoFitTextureView textTrueView) {

        if (textTrueView.isAvailable()) {
            FaceDetectSDK.with().openCamera(textTrueView, context, textTrueView.getWidth(), textTrueView.getHeight());
        } else {
            textTrueView.setSurfaceTextureListener(surfaceTextureListener);
        }

        this.mContext = context;
        this.mTextTrueView = textTrueView;

        //重置数据
        resetMotionsList();
        if (!isSetMotions) {
            //先随机看几种验证方式
            mMotionSum = Constants.MOTIONS_NUM;
            //随机的最后校验顺序
            mLastMotions = getRandomTypeFromMotionsList(mMotionSum);
        }

        //重置数据
        resetMotionsList();

        return this;
    }


    /**
     * Starts a background thread and its {@link Handler}.
     */
    @DebugLog
    private void startBackgroundThread() {
        backgroundThread = new HandlerThread("ImageListener");
        backgroundThread.start();
        backgroundHandler = new Handler(backgroundThread.getLooper());

        inferenceThread = new HandlerThread("InferenceThread");
        inferenceThread.start();
        inferenceHandler = new Handler(inferenceThread.getLooper());
    }

    /**
     * Stops the background thread and its {@link Handler}.
     */
    @SuppressLint("LongLogTag")
    @DebugLog
    private void stopBackgroundThread() {
        backgroundThread.quitSafely();
        inferenceThread.quitSafely();
        try {
            backgroundThread.join();
            backgroundThread = null;
            backgroundHandler = null;

            inferenceThread.join();
            inferenceThread = null;
            inferenceHandler = null;
        } catch (final InterruptedException e) {
            e.printStackTrace();
        }
    }

    /**
     * 设置监听
     */
    public FaceDetectSDK setFaceDetectListener(FaceDetectListener listener) {
        this.mListener = listener;
        return this;
    }

    public FaceDetectSDK setMotionList(ArrayList<Integer> motions, boolean isRandom) {
        mMotionSum = motions.size();
        if (isRandom) {
            Collections.shuffle(motions);
            this.mLastMotions = motions;
        } else {
            this.mLastMotions = motions;
        }

        isSetMotions = true;

        return this;
    }

    /**
     * 设置只检测张嘴
     */
    public FaceDetectSDK setMouthMotionType(boolean isOnlyMouth) {
        this.isOnlyMouth = isOnlyMouth;

        return this;
    }

    /**
     * 设置只检测摇头
     */
    public FaceDetectSDK setHeadMotionType(boolean isOnlyHead) {
        this.isOnlyHead = isOnlyHead;

        return this;
    }

    /**
     * 设置只检测眨眼
     */
    public FaceDetectSDK setEyeMotionType(boolean isOnlyEye) {
        this.isOnlyEye = isOnlyEye;
        return this;
    }

    /**
     * 从校验类型中随机获取sum种类型
     */
    private ArrayList<Integer> getRandomTypeFromMotionsList(int sum) {
        ArrayList<Integer> motions = new ArrayList<>(sum);
        Random random = new Random();

        if (sum == 1) {
            if (isOnlyMouth) {
                motions.add(Constants.MOTION_MOUTH);
            } else if (isOnlyEye) {
                motions.add(Constants.MOTION_EYE);
            } else if (isOnlyHead) {
                motions.add(Constants.MOTION_HEAD);
            } else {
                for (int i = 0; i < sum; i++) {
                    int index = random.nextInt(mMotions.size());
                    motions.add(mMotions.get(index));
                    mMotions.remove(index);
                }
            }
        } else {
            for (int i = 0; i < sum; i++) {
                int index = random.nextInt(mMotions.size());
                motions.add(mMotions.get(index));
                mMotions.remove(index);
            }
        }


        //打乱顺序
        Collections.shuffle(motions);
        return motions;
    }

    private CameraCaptureSession.CaptureCallback getCaptureCallback() {
        return new CameraCaptureSession.CaptureCallback() {
            @Override
            public void onCaptureProgressed(
                    @NonNull final CameraCaptureSession session,
                    @NonNull final CaptureRequest request,
                    @NonNull final CaptureResult partialResult) {
            }

            @Override
            public void onCaptureCompleted(
                    @NonNull final CameraCaptureSession session,
                    @NonNull final CaptureRequest request,
                    @NonNull final TotalCaptureResult result) {
            }
        };
    }


    /**
     * Given {@code choices} of {@code Size}s supported by a camera, chooses the smallest one whose
     * width and height are at least as large as the respective requested values, and whose aspect
     * ratio matches with the specified value.
     *
     * @param choices     The list of sizes that the camera supports for the intended output class
     * @param width       The minimum desired width
     * @param height      The minimum desired height
     * @param aspectRatio The aspect ratio
     * @return The optimal {@code Size}, or an arbitrary one if none were big enough
     */
    private Size chooseOptimalSize(
            final Size[] choices, final int width, final int height, final Size aspectRatio) {
        // Collect the supported resolutions that are at least as big as the preview Surface
        final List<Size> bigEnough = new ArrayList<>();
        for (final Size option : choices) {
            if (option.getHeight() >= mMinPreSize && option.getWidth() >= mMinPreSize) {
                Log.i("FaceDetectSDK", "Adding size: " + option.getWidth() + "x" + option.getHeight());
                bigEnough.add(option);
            } else {
                Log.i("FaceDetectSDK", "Not adding size: " + option.getWidth() + "x" + option.getHeight());
            }
        }


        // Pick the smallest of those, assuming we found any
        if (bigEnough.size() > 0) {
            final Size chosenSize = Collections.min(bigEnough, new CompareSizesByArea());
            Log.i("FaceDetectSDK", "Chosen size: " + chosenSize.getWidth() + "x" + chosenSize.getHeight());
            return chosenSize;
        } else {
            Log.i("FaceDetectSDK", "Couldn't find any suitable preview size");
            return choices[0];
        }
    }

    private class CompareSizesByArea implements Comparator<Size> {
        @Override
        public int compare(final Size lhs, final Size rhs) {
            // We cast here to ensure the multiplications won't overflow
            return Long.signum(
                    (long) lhs.getWidth() * lhs.getHeight() - (long) rhs.getWidth() * rhs.getHeight());
        }

    }

    /**
     * Sets up member variables related to camera.
     *
     * @param width  The width of available size for camera preview
     * @param height The height of available size for camera preview
     */
    private void setUpCameraOutputs(Context context, AutoFitTextureView textureView
            , final int width, final int height) {
        final CameraManager manager = (CameraManager) context.getSystemService(Context.CAMERA_SERVICE);
        try {
            @SuppressLint("UseSparseArrays")
            SparseArray<Integer> cameraFaceTypeMap = new SparseArray<>();
            if (manager == null) {
                return;
            }
            // 检查相机设备的正面类型
            for (final String cameraId : manager.getCameraIdList()) {
                final CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraId);
                final Integer facing = characteristics.get(CameraCharacteristics.LENS_FACING);

                if (facing != null && facing == CameraCharacteristics.LENS_FACING_FRONT) {
                    if (cameraFaceTypeMap.get(CameraCharacteristics.LENS_FACING_FRONT) != null) {
                        cameraFaceTypeMap.append(CameraCharacteristics.LENS_FACING_FRONT
                                , cameraFaceTypeMap.get(CameraCharacteristics.LENS_FACING_FRONT) + 1);
                    } else {
                        cameraFaceTypeMap.append(CameraCharacteristics.LENS_FACING_FRONT, 1);
                    }
                }

                if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK) {
                    if (cameraFaceTypeMap.get(CameraCharacteristics.LENS_FACING_FRONT) != null) {
                        cameraFaceTypeMap.append(CameraCharacteristics.LENS_FACING_BACK
                                , cameraFaceTypeMap.get(CameraCharacteristics.LENS_FACING_BACK) + 1);
                    } else {
                        cameraFaceTypeMap.append(CameraCharacteristics.LENS_FACING_BACK, 1);
                    }
                }
            }

            Integer num_facing_back_camera = cameraFaceTypeMap.get(CameraCharacteristics.LENS_FACING_BACK);
            for (final String cameraId : manager.getCameraIdList()) {
                final CameraCharacteristics characteristics = manager.getCameraCharacteristics(cameraId);
                final Integer facing = characteristics.get(CameraCharacteristics.LENS_FACING);
                // 如果存在面向后置摄像头或面向外置摄像头，则我们不会使用面向前置摄像头
                if (num_facing_back_camera != null && num_facing_back_camera > 0) {
                    // 如果还有其他面向相机的设备类型，则在此示例中我们不使用前置摄像头
                    if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK) {
                        continue;
                    }
                }

                final StreamConfigurationMap map =
                        characteristics.get(CameraCharacteristics.SCALER_STREAM_CONFIGURATION_MAP);

                if (map == null) {
                    continue;
                }

                // 对于静态图像捕获，我们使用最大的可用尺寸.
                final Size largest =
                        Collections.max(
                                Arrays.asList(map.getOutputSizes(ImageFormat.YUV_420_888)),
                                new CompareSizesByArea());

                // Danger, W.R.! Attempting to use too large a preview size could  exceed the camera
                // bus' bandwidth limitation, resulting in gorgeous previews but the storage of
                // garbage capture data.
                mPreviewSize = chooseOptimalSize(map.getOutputSizes(SurfaceTexture.class), width, height, largest);

                // We fit the aspect ratio of TextureView to the size of preview we picked.
                final int orientation = context.getResources().getConfiguration().orientation;
                if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
                    textureView.setAspectRatio(mPreviewSize.getWidth(), mPreviewSize.getHeight());
                } else {
                    textureView.setAspectRatio(mPreviewSize.getHeight(), mPreviewSize.getWidth());
                }
                return;
            }
        } catch (final CameraAccessException | NullPointerException e) {
            e.printStackTrace();
        }

    }

    public void onPause() {
        stopBackgroundThread();

        try {
            cameraOpenCloseLock.acquire();
            if (null != captureSession) {
                captureSession.close();
                captureSession = null;
            }
            if (null != cameraDevice) {
                cameraDevice.close();
                cameraDevice = null;
            }
            if (null != previewReader) {
                previewReader.close();
                previewReader = null;
            }
            if (null != mOnGetPreviewListener) {
                mOnGetPreviewListener.deInitialize();
            }
        } catch (final InterruptedException e) {
            throw new RuntimeException("Interrupted while trying to lock camera closing.", e);
        } finally {
            cameraOpenCloseLock.release();
        }
    }


    /**
     * Configures the necessary {@link Matrix} transformation to `mTextureView`.
     * This method should be called after the camera preview size is determined in
     * setUpCameraOutputs and also the size of `mTextureView` is fixed.
     *
     * @param viewWidth  The width of `mTextureView`
     * @param viewHeight The height of `mTextureView`
     */
    public void configureTransform(Activity activity, AutoFitTextureView textureView
            , final int viewWidth, final int viewHeight) {
        if (null == textureView || null == mPreviewSize || null == activity) {
            return;
        }
        final int rotation = activity.getWindowManager().getDefaultDisplay().getRotation();
        final Matrix matrix = new Matrix();
        final RectF viewRect = new RectF(0, 0, viewWidth, viewHeight);
        final RectF bufferRect = new RectF(0, 0, mPreviewSize.getHeight(), mPreviewSize.getWidth());
        final float centerX = viewRect.centerX();
        final float centerY = viewRect.centerY();
        if (Surface.ROTATION_90 == rotation || Surface.ROTATION_270 == rotation) {
            bufferRect.offset(centerX - bufferRect.centerX(), centerY - bufferRect.centerY());
            matrix.setRectToRect(viewRect, bufferRect, Matrix.ScaleToFit.FILL);
            final float scale =
                    Math.max(
                            (float) viewHeight / mPreviewSize.getHeight(),
                            (float) viewWidth / mPreviewSize.getWidth());
            matrix.postScale(scale, scale, centerX, centerY);
            matrix.postRotate(90 * (rotation - 2), centerX, centerY);
        } else if (Surface.ROTATION_180 == rotation) {
            matrix.postRotate(180, centerX, centerY);
        }
        textureView.setTransform(matrix);
    }

    public void openCamera(AutoFitTextureView textureView, Activity activity, final int width, final int height) {
        Log.d("FaceDetectSDK", "width " + width + "height " + height);
        setUpCameraOutputs(activity, textureView, width, height);
        configureTransform(activity, textureView, width, height);
        final CameraManager manager = (CameraManager) activity.getSystemService(Context.CAMERA_SERVICE);
        if (manager == null) {
            return;
        }

        try {
            if (!cameraOpenCloseLock.tryAcquire(2500, TimeUnit.MILLISECONDS)) {
                throw new RuntimeException("Time out waiting to lock camera opening.");
            }
            if (ActivityCompat.checkSelfPermission(activity, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                Log.d("FaceDetectSDK", "checkSelfPermission CAMERA");
            }
            //we just use facing front camera to detect
            manager.openCamera("1", stateCallback, backgroundHandler);
            Log.d("FaceDetectSDK", "open Camera");
        } catch (final CameraAccessException e) {
            Log.d("FaceDetectSDK", "Exception!", e);
        } catch (final InterruptedException e) {
            throw new RuntimeException("Interrupted while trying to lock camera opening.", e);
        }
    }

    private final CameraDevice.StateCallback stateCallback =
            new CameraDevice.StateCallback() {
                @Override
                public void onOpened(@NonNull final CameraDevice cd) {
                    // This method is called when the camera is opened.  We start camera preview here.
                    cameraOpenCloseLock.release();
                    cameraDevice = cd;
                    createCameraPreviewSession();
                }

                @Override
                public void onDisconnected(final CameraDevice cd) {
                    cameraOpenCloseLock.release();
                    cd.close();
                    cameraDevice = null;

                    if (mOnGetPreviewListener != null) {
                        mOnGetPreviewListener.deInitialize();
                    }
                }

                @Override
                public void onError(final CameraDevice cd, final int error) {
                    cameraOpenCloseLock.release();
                    cd.close();
                    cameraDevice = null;
//                    final Activity activity = getActivity();
//                    if (null != activity) {
//                        activity.finish();
//                    }

                    if (mOnGetPreviewListener != null) {
                        mOnGetPreviewListener.deInitialize();
                    }
                }
            };


    private void createCameraPreviewSession() {
        try {
            final SurfaceTexture texture = mTextTrueView.getSurfaceTexture();

            // 我们将默认缓冲区的大小配置为所需的摄像机预览的大小
            texture.setDefaultBufferSize(mPreviewSize.getWidth(), mPreviewSize.getHeight());
            //texture.setOnFrameAvailableListener();

            // 这是我们需要开始预览的输出Surface.
            final Surface surface = new Surface(texture);

            // 我们使用输出Surface设置一个CaptureRequest.Builder
            previewRequestBuilder = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);
            previewRequestBuilder.addTarget(surface);

            // 设置预览画面的帧率 视实际情况而定选择一个帧率范围
//            previewRequestBuilder.set(CaptureRequest.CONTROL_AE_TARGET_FPS_RANGE, fpsRanges[0]);

            // 为预览框架创建阅读器
            previewReader =
                    ImageReader.newInstance(
                            mPreviewSize.getWidth(), mPreviewSize.getHeight(), ImageFormat.YUV_420_888, 2);

            previewReader.setOnImageAvailableListener(mOnGetPreviewListener, backgroundHandler);
            previewRequestBuilder.addTarget(previewReader.getSurface());

            // 在这里，我们创建了CameraCaptureSession来进行相机预览
            cameraDevice.createCaptureSession(
                    Arrays.asList(surface, previewReader.getSurface()), new CameraCaptureSession.StateCallback() {
                        @Override
                        public void onConfigured(@NonNull final CameraCaptureSession cameraCaptureSession) {
                            // 相机已经关闭
                            if (null == cameraDevice) {
                                return;
                            }

                            // 会话准备就绪后，我们开始显示预览.
                            captureSession = cameraCaptureSession;
                            try {
                                // 自动对焦应连续进行相机预览.
                                previewRequestBuilder.set(
                                        CaptureRequest.CONTROL_AF_MODE,
                                        CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);
                                // 必要时会自动启用闪光灯.
                                previewRequestBuilder.set(
                                        CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH);

                                // 最后，我们开始显示摄像机预览。
                                previewRequest = previewRequestBuilder.build();
                                captureSession.setRepeatingRequest(
                                        previewRequest, getCaptureCallback(), backgroundHandler);
                            } catch (final CameraAccessException e) {
                                e.printStackTrace();
                            }
                        }

                        @Override
                        public void onConfigureFailed(@NonNull final CameraCaptureSession cameraCaptureSession) {
                            Log.d("FaceDetectSDK", "Failed");
                        }
                    },
                    null);

            mOnGetPreviewListener.initialize(mContext, inferenceHandler, mLastMotions, mListener);
            mListener.onReady();
        } catch (final CameraAccessException e) {
            e.printStackTrace();
        }
    }


    /**
     * {@link android.view.TextureView.SurfaceTextureListener} handles several lifecycle events on a
     * {@link TextureView}.
     */
    private final TextureView.SurfaceTextureListener surfaceTextureListener =
            new TextureView.SurfaceTextureListener() {
                @Override
                public void onSurfaceTextureAvailable(
                        final SurfaceTexture texture, final int width, final int height) {
                    openCamera(mTextTrueView, mContext, width, height);
                }

                @Override
                public void onSurfaceTextureSizeChanged(
                        final SurfaceTexture texture, final int width, final int height) {
                    configureTransform(mContext, mTextTrueView, width, height);
                }

                @Override
                public boolean onSurfaceTextureDestroyed(final SurfaceTexture texture) {
                    return true;
                }

                @Override
                public void onSurfaceTextureUpdated(final SurfaceTexture texture) {
                }
            };
}
